site_name: Foundations of Programming
site_description: Building a foundation for a lifelong journey into software engineering
site_author: Jason Barr <me@jasonbarr.dev>
copyright: "&copy; 2020 Jason S. Barr. All rights reserved."
theme:
  name: mkdocs
  hljs_style: darcula
extra_css:
  - css/app.css
extra_javascript:
  - js/app.js
nav:
  - Home: index.md
  - Introduction:
    - Computers and computing: intro/computers.md
